# Kronecker Product demo with 2x2 matrices

## kronecker product formular:  vec(AXB)  = ($B^T$⊗A)vec(X)

In [19]:
import numpy as np

In [20]:
#2x2 matrices for A, X, B
A =np.array([[1, 2], [3, 4]])
X = np.array([[5, 6], [7, 8]])
B = np.array([[9, 8], [7, 6]])

print("A:",A)
print("X:",X)  
print("B:",B)

A: [[1 2]
 [3 4]]
X: [[5 6]
 [7 8]]
B: [[9 8]
 [7 6]]


In [34]:
#vectorized X
vec_X= X.T.reshape(-1)
print("Vectorized X:",vec_X)
print("vec(X) shape:",vec_X.shape)

Vectorized X: [5 7 6 8]
vec(X) shape: (4,)


##### vec(AXB)

In [39]:
vecAXB=(A@X@B).T.reshape(-1)
print("Vectorized AXB:",vecAXB)
print("vec(AXB) shape:",vecAXB.shape)

Vectorized AXB: [325 737 284 644]
vec(AXB) shape: (4,)


#### ($B^T$ ⊗ A)

In [36]:
BT = B.T

lst_matrices= []
for i in range(BT.shape[0]):
    tmp_lst_row =[]
    for j in BT[i]:
        tmp_lst_row.append(j*A)
    lst_matrices.append(tmp_lst_row)

#(B^T ⊗ A)
BT_kron_A = np.block(lst_matrices)

print("(B^T ⊗ A):",BT_kron_A)
print("(B^T ⊗ A) shape:",BT_kron_A.shape)

(B^T ⊗ A): [[ 9 18  7 14]
 [27 36 21 28]
 [ 8 16  6 12]
 [24 32 18 24]]
(B^T ⊗ A) shape: (4, 4)


#### ($B^T$ ⊗ A)vec(X)

In [37]:
kron_prod_res = BT_kron_A@vec_X
print("(B^T ⊗ A) vec(X):",kron_prod_res)
print("(B^T ⊗ A) vec(X) shape:",kron_prod_res.shape)

(B^T ⊗ A) vec(X): [325 737 284 644]
(B^T ⊗ A) vec(X) shape: (4,)
